# -*- coding: utf-8 -*-
"""AGE_CALCULATOR.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KDekc8jZ6-fymNS-dvoxGVzFqQWU6HqF
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st
from datetime import date

st.title("Age Calculator")

dob = st.date_input("Select DOB")

if st.button("Calculate"):
    today=date.today()
    age=today.year-dob.year

    st.success(f"Age: {age} years")