# -*- coding: utf-8 -*-
"""Untitled22.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/18RdLYIEYxCwpW3OSCqpm8GUsuUQIxIOx
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install streamlit
import streamlit as st
st.title("🎓 Student Information Form")
st.write("Enter student details and view the submitted information.")
student_name = st.text_input("Enter Student Name")

roll_number = st.number_input(
    "Enter Roll Number",
    min_value=1,
    step=1
)

course = st.selectbox(
    "Select Course",
    ["BCA", "B.Tech", "B.Sc", "MCA", "MBA", "M.Tech"]
)

subjects = st.multiselect(
    "Select Subjects",
    ["Python", "Java", "DBMS", "Data Structures", "Web Development", "Machine Learning"]
)

marks = st.slider(
    "Select Marks",
    min_value=0,
    max_value=100,
    value=50
)

if st.button("Submit"):
    st.success("Student details submitted successfully!")

    st.subheader("📋 Student Details")

    st.write(f"**Student Name:** {student_name}")
    st.write(f"**Roll Number:** {roll_number}")
    st.write(f"**Course:** {course}")

    if subjects:
        st.write(f"**Subjects:** {', '.join(subjects)}")
    else:
        st.write("**Subjects:** None Selected")

    st.write(f"**Marks:** {marks}")